src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 * @Vich\Uploadable
 */
class Annonce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $Prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonce")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

     /**
     * @Vich\UploadableField(mapping="produits_image", fileNameProperty="Image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
  
    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="annonce")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }
  
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at)
    {
        $this->updated_at = $updated_at;
    }
  
    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\IdentificationType;
use Doctrine\ORM\EntityManagerInterface;
use App\Notification\ContactNotification;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/security", name="security")
     */
    public function index()
    {
        return $this->render('security/index.html.twig', [
            'controller_name' => 'SecurityController',
        ]);
    }

    /**
     * @Route("/registration", name="registration")
     */
    public function registration(Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder, AuthenticationUtils $authenticationUtils, ContactNotification $notification)
    {
        $user = new User;

        $form = $this->createForm(IdentificationType::class, $user); 

        dump($request);

        $form->handleRequest($request);
        $user->setRoles(['ROLE_USER']);
        $error = $authenticationUtils->getLastAuthenticationError();


        if($form->isSubmitted() && $form->isValid())
        {
            $notification->notify($user);
            $this->addFlash('successs', 'Votre Email a bien été envoyé');
            $user->setCreatedAt(new \DateTime());
            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash); 
            $manager->persist($user);
            $manager->flush();

            $this->addFlash('success', 'Félicitation ! Vous êtes maintenant inscrit !');
            return $this->redirectToRoute('security_login');
        }

        return $this->render('security/registration.html.twig', [
            'formIdentification' => $form->createView(),
            'error' => $error,
            'errorAge' => "Vous devez avoir au moin 18 ans pour vous inscrire"
        ]);
    }

    /**
     * @Route("/blog/{id}/profil", name="modifierProfil")
     */
    public function registrations(User $user = null, Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder, AuthenticationUtils $authenticationUtils)
    {
        if(!$user)
        {
            $user = new User;
        }

        $form = $this->createForm(IdentificationType::class, $user); 

        $user->setRoles(['ROLE_USER']);
        $form->handleRequest($request);

        // $error = $authenticationUtils->getLastAuthenticationError();


        if($form->isSubmitted() && $form->isValid())
        {
            // if(!$user->getId())
            // {
            //     $user->setCreatedAt(new \DateTime);
            // }

            $user->setCreatedAt(new \DateTime());

            $hash = $encoder->encodePassword($user, $user->getPassword());


            $user->setPassword($hash); 

            $manager->persist($user);
            $manager->flush();

            $this->addFlash('success', 'Vos modifications ont été enregistrées avec succès !');
        
        }

        return $this->render('security/information_personnel.html.twig',[
            'formDonneePersonnel' => $form->createView(),
            'editMode' => $user->getId()!== null,
            'imgs'=> $user->getImage(),
            'pseudo'=> $user->getPseudo(),
            'mail'=> $user->getEmail(),
            'userid'=> $user->getId(),
        ]);
    }

    /**

     * @Route("/connexion", name="security_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response 
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error
        ]);
    }

    /**
     * @Route("/deconnexion", name="security_logout")
     */
    public function logout()
    {
    }
        

    /**
     * @Route("registration/cgv", name="CGV")
     */
    public function cgv()
    {
        return $this->render('security/cgv.html.twig');
    }

    /**
     * @Route("registration/cgu", name="CGU")
     */
    public function cgu()
    {
        return $this->render('security/cgu.html.twig');
    }

    /**
     * @Route("registration/politique", name="politique_de_confidentialite")
     */
    public function politique_confidentialite()
    {
        return $this->render('security/politiqueConfidentialite.html.twig');

    }
}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SecurityController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/ProjetWF3/ProjetWf3/src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/ProjetWF3/ProjetWf3/templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/information_personnel.html.twig
{% extends 'base.html.twig' %} 


{% block body %}


<h3 class="my-4 mx-auto text-center">Information personnel</h3>


<div class="col-md-11 mx-auto d-flex justify-content-center mt-5 mb-5 border p-3 info-perso">
    <div class="col-md-6 rounded mr-3 mb-3 mb-sm-0">
        <div id="colorPerso" class=" col-md-12 mx-auto rounded d-flex flex-column justify-content-center text-white text-center p-3 border border-secondary">
            {# <img class="mt-4 mx-1 rounded border-top border-dark " src="{{ app.user.image|replace({" 640/480 ": "350/210 "}) }}"> #}
            <img class="mt-4 mx-1 rounded border-top border-dark" src="{{ asset('images/produits/' ~ imgs ) }}" alt="Card image cap">
            <hr>
            <p id="divInfoPersoOff" class="p-2 rounded  border-top border-dark ">{{ pseudo }}</p>
            <p id="divInfoPersoOff" class="p-2 rounded border-top border-dark "><i class="far fa-envelope mr-2"></i>{{ mail|raw }}</p>
            <a id="divInfoPersoOn" class="p-2 rounded  text-white text-decoration-none border-top border-dark" href="{{ path('annonce_personnel', {'id': userid}) }}">Ma page personnel</a>
        </div>
    </div>

    <div class="col-md-6 border-left">
        <div id="colorPerso" class="col-md-12 d-flex rounded border border-secondary">


            {{ form_start( formDonneePersonnel, { 'attr' : { 'class' : 'col-md-12 rounded p-3 text-white mb-5 ' }}) }} 
            {{ form_row(formDonneePersonnel.imageFile, { 'label' : "Photo de profil"}) }} 
            {{ form_row(formDonneePersonnel.prenom) }} 
            {{ form_row(formDonneePersonnel.nom) }} 
            {{ form_row(formDonneePersonnel.email) }} 
            {{ form_row(formDonneePersonnel.ville) }} 
            {{ form_row(formDonneePersonnel.password, { 'label' : "Mot de passe"}) }} 
            {{ form_row(formDonneePersonnel.confirm_password, { 'label' : "Confirmez votre mot de passe"}) }} 
            {{ form_row(formDonneePersonnel.adresse) }} 
            {{ form_row(formDonneePersonnel.pseudo) }} 
            {{ form_row(formDonneePersonnel.civilite) }} 
            {{ form_row(formDonneePersonnel.birth, { 'label' : "Date de naissance"}) }} 
            {{ form_row(formDonneePersonnel.telephone, { 'label' : "Telephone"}) }} 

                <div class="col-md-12 d-flex justify-content-end">
                    <button id="colorBtnInputy " class="btn btn-dark rounded" type="submit">Modifier</button>
                </div>

            {{ form_end(formDonneePersonnel) }} 
        </div>

    

    </div>
</div>





{# {% endif %} #} {# {{ dump(app); }} #} {% endblock %}

templates/security/login.html.twig
{% extends "base.html.twig" %} 

{% block body %}

    <h1 class="display-4 text-center mt-2 mb-5">Bonjour!</h1>

    {% if error %}

        <p class="bg-danger text-white text-center p-2 col-md-3 m-3 mx-auto rounded">{{ error.messageKey|trans(error.messageData, 'security') }}</p>

    {% endif %}

    
        <form action="{{ path('security_login') }}" method="post" class="col-md-5 mx-auto form-connexion">
            
            <div id="colorBtnInput" class="form-group rounded border border-secondary">
                <label class="ml-2" for="_username">Email</label>
                <input type="text" class="form-control" name="_username" placeholder="Adresse email..." required="_username" value="{{ last_username }}">

            </div>


            <div id="colorBtnInput" class="form-group rounded border border-secondary">
                <label class="ml-2" for="_password">Mot de passe</label>
                <input type="password" class="form-control" name="_password" placeholder="Mot de passe..." required="_password">
            </div>

            <div class="d-flex justify-content-around mb-3">
                <input id="colorBtnInput" type="submit" value="Connexion" class="btn">
            </div>
            <em>
        
        </form>
    


        <div class="d-flex justify-content-center">
            <p>Pas encore de compte? <strong><a href="{{ path('registration') }}">Créer un compte</a></strong> </p>
        </div>
    </em>
{% endblock %}

templates/security/politiqueConfidentialite.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <h1 class="display-4 my-5 text-center">Politique de confidentialité</h1>

    <div class="my-5 mx-auto col-md-8">

        <h2>1.Collecte de l’information</h2>
        <p>Nous recueillons des informations lorsque vous vous inscrivez sur notre site, lorsque vous vous connectez à votre compte, faites un achat, participez à un concours, et / ou lorsque vous vous déconnectez. Les informations recueillies incluent votre nom, votre adresse e-mail, numéro de téléphone, et / ou carte de crédit.
        En outre, nous recevons et enregistrons automatiquement des informations à partir de votre ordinateur et navigateur, y compris votre adresse IP, vos logiciels et votre matériel, et la page que vous demandez.</p>
        

        <h2>2. Utilisation des informations</h2>
        Toutes les informations que nous recueillons auprès de vous peuvent être utilisées pour :
        - Personnaliser votre expérience et répondre à vos besoins individuels
        - Fournir un contenu publicitaire personnalisé
        - Améliorer notre site
        - Améliorer le service client et vos besoins de prise en charge
        - Vous contacter par e-mail
        - Administrer un concours, une promotion, ou une enquête
        

        <h2>3. Confidentialité du commerce en ligne</h2>
        Nous sommes les seuls propriétaires des informations recueillies sur ce site. Vos informations personnelles ne seront pas vendues, échangées, transférées, ou données à une autre société pour n’importe quelle raison, sans votre consentement, en dehors de ce qui est nécessaire pour répondre à une demande et / ou une transaction, comme par exemple pour expédier une commande.
            

        <h2>4. Divulgation à des tiers</h2>
        Nous ne vendons, n’échangeons et ne transférons pas vos informations personnelles identifiables à des tiers. Cela ne comprend pas les tierce parties de confiance qui nous aident à exploiter notre site Web ou à mener nos affaires, tant que ces parties conviennent de garder ces informations confidentielles.

        Nous pensons qu’il est nécessaire de partager des informations afin d’enquêter, de prévenir ou de prendre des mesures concernant des activités illégales, fraudes présumées, situations impliquant des menaces potentielles à la sécurité physique de toute personne, violations de nos conditions d’utilisation, ou quand la loi nous y contraint.

        Les informations non-privées, cependant, peuvent être fournies à d’autres parties pour le marketing, la publicité, ou d’autres utilisations.
            

        <h2>5. Protection des informations</h2>
        Nous mettons en œuvre une variété de mesures de sécurité pour préserver la sécurité de vos informations personnelles. Nous utilisons un cryptage à la pointe de la technologie pour protéger les informations sensibles transmises en ligne. Nous protégeons également vos informations hors ligne. Seuls les employés qui ont besoin d’effectuer un travail spécifique (par exemple, la facturation ou le service à la clientèle) ont accès aux informations personnelles identifiables. Les ordinateurs et serveurs utilisés pour stocker des informations personnelles identifiables sont conservés dans un environnement sécurisé.
            
        Est-ce que nous utilisons des cookies ?
        Nos cookies améliorent l’accès à notre site et identifient les visiteurs réguliers. En outre, nos cookies améliorent l’expérience d’utilisateur grâce au suivi et au ciblage de ses intérêts. Cependant, cette utilisation des cookies n’est en aucune façon liée à des informations personnelles identifiables sur notre site.
            

        <h2>6. Se désabonner</h2>
        Nous utilisons l’adresse e-mail que vous fournissez pour vous envoyer des informations et mises à jour relatives à votre commande, des nouvelles de l’entreprise de façon occasionnelle, des informations sur des produits liés, etc. Si à n’importe quel moment vous souhaitez vous désinscrire et ne plus recevoir d’e-mails, des instructions de désabonnement détaillées sont incluses en bas de chaque e-mail.
            

        <h2>7. Consentement</h2>
        En utilisant notre site, vous consentez à notre politique de confidentialité.

    </div>
{% endblock %}

templates/security/registration.html.twig
{% extends 'base.html.twig' %} 

{% block body %}

<h1 class="display-4 my-4 mx-auto text-center">Inscription</h1>



    {{ form_start(formIdentification, { 'attr' : { 'class' : 'col-md-6 mx-auto mb-5 rounded border border-secondary p-2', 'id':'divInfoPersoOff' }}) }}
    
        {{ form_row(formIdentification.prenom,{'id' : 'colorBtnInput','class' :'rounded border border-secondary'})}}
        {{ form_row(formIdentification.nom,{'id' : 'colorBtnInput' })}}
        {{ form_row(formIdentification.civilite,{'id' : 'colorBtnInput' }) }}
        {{ form_row(formIdentification.email,{'id' : 'colorBtnInput' }) }}
        {{ form_row(formIdentification.telephone,{'id' : 'colorBtnInput' }) }}
        {{ form_row(formIdentification.pseudo,{'id' :'colorBtnInput' }) }}
        {{ form_row(formIdentification.password, {'label' : 'Mot de passe','id':'colorBtnInput'}) }}
        {{ form_row(formIdentification.confirm_password, {'label' : 'Confirmez votre mot de passe', 'id' : 'colorBtnInput'}) }}
        {{ form_row(formIdentification.ville,{'id': 'colorBtnInput' }) }}
        {{ form_row(formIdentification.adresse,{'id' : 'colorBtnInput' }) }}
        {{ form_row(formIdentification.birth, {'label' : 'Date de naissance' , 'attr' : { 'class' : 'col-md-4' }, 'id' : 'colorBtnInput' }) }}
        {# {{ form_row(formIdentification.birth,
        {'label' : 'Date de naissance' , 'attr' : { 'class' : 'col-md-4' } }) }} #}
        {{ form_row(formIdentification.imageFile, {'label' : 'Image de profil'}) }}

       {# {{ form_row(formIdentification.image, {'label' : 'Photo de profil'}) }} #}


        <div>
            <input class="form-controle mr-2" type="checkbox" id="cgv" name="cgv" required="true" oninvalid="this.setCustomValidity('Veuillez acceptez les Conditions Générale de Ventes')" oninput="setCustomValidity('')">
            <label for="cgv">J'accepte les <a href="{{ path('CGV') }}">Conditions Générales de Ventes et d'Utilisation</a></label><br>
        </div>
        <div class="mb-4">
            <input class="form-controle mr-2" type="checkbox" id="politiqueConfidentialite" name="politiqueConfidentialite" required="true" oninvalid="this.setCustomValidity('Veuillez acceptez notre Politique de Confidentialité')" oninput="setCustomValidity('')">
            <label for="cgv">J'accepte la <a href="{{ path('politique_de_confidentialite') }}">Politique de Confidentialité</a></label><br>
        </div>
      
        <button id="divInfoPersoOn" class="btn col-md-2" type="submit">S'incrire</button>
    {{ form_end(formIdentification,{'id' : 'colorBtnInput' }) }}<hr>
    
{% endblock %}
 