src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 * @Vich\Uploadable
 */
class Annonce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $Prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonce")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

     /**
     * @Vich\UploadableField(mapping="produits_image", fileNameProperty="Image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
  
    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="annonce")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }
  
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at)
    {
        $this->updated_at = $updated_at;
    }
  
    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;



/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @Vich\Uploadable
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cette Email est déjà utilisée !",
 * )
 * @UniqueEntity(
 *  fields={"pseudo"},
 *  message="Ce pseudo est déjà utilisée !",
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 2, minMessage = "Veuillez saisir un prénom valide.")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 2, minMessage = "Veuillez saisir un nom valide.")
     * 
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 3, minMessage = "Votre pseudo doit contenir au minimum 3 caractères.")
     * 
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 3, minMessage = "Veuillez saisir une ville.")
     */
    private $ville;

    /** 
     * @ORM\Column(type="string", length=255)
     */
    private $civilite;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 3, minMessage = "Veuillez saisir votre adresse.")
     * 
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 8, minMessage = "Votre mot de passe doit faire au minimum 8 caractères")
     * @Assert\EqualTo(propertyPath="confirm_password", message="Les mots de passes ne correspondent pas")
     */
    private $password;

    public $confirm_password;

    /**
     * @ORM\Column(type="date")
     * @Assert\LessThanOrEqual("-16 years", message="Vous devez avoir au moin 16 ans pour vous inscrire.")
     */
    private $birth;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email
     */
    private $email;

    public $cgv;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    private $Username;

    private $eraseCredentials;

    private $salt;

    /**
     * @ORM\OneToMany(targetEntity=Annonce::class, mappedBy="user")
     */
    private $annonce;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="produits_image", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="json")
     */
    private $Roles = [];

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 10, max = 10, minMessage = "min_lenght", maxMessage = "max_lenght")
     * @Assert\Regex(pattern="/^[0-9]*$/", message="number_only") 
     */
    private $telephone;

 
    // /**
    //  * @ORM\Column(type="string", length=255)
    //  */
    // private $telephone;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->annonce = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBirth(): ?\DateTimeInterface
    {
        return $this->birth;
    }

    public function setBirth(\DateTimeInterface $birth): self
    {
        $this->birth = $birth;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername()
    {
        
    }

    public function eraseCredentials()
    {
        
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function getRoles()
    {
        return $this->Roles;
        // return ['ROLES_USER'];
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonce(): Collection
    {
        return $this->annonce;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonce->contains($annonce)) {
            $this->annonce[] = $annonce;
            $annonce->setUser($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonce->contains($annonce)) {
            $this->annonce->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getUser() === $this) {
                $annonce->setUser(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
    
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function __toString()
    {
        return $this->prenom;
    }

    public function setRoles($Roles)
    {
        // $Roles = ["ROLE_USER"];
        $this->Roles = $Roles;

        return $this;
    }


    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

    }
    
    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;


        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Annonce;
use App\Entity\Category;
use App\Form\Annonce2Type;
use App\Form\AnnonceFormType;

use App\Form\IdentificationType;
use App\Form\DonneePersonnelType;
use App\Repository\UserRepository;
use App\Form\SelectionCategoryType;
use App\Repository\AnnonceRepository;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\Null_;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class BlogController extends AbstractController
{
    
     /**
     * @Route("blog/new", name="blog_create")
     * @Route("/blog/{id}/edit", name="blogEdit")
     */
    public function formulaire(Annonce $annonce = null, Request $request, EntityManagerInterface $manager)
    {
        if(!$annonce)
        {
            $annonce = new Annonce();
        }

        $id = $this->getUser()->getId();
        $repo = $this->getDoctrine()->getRepository(User::class);
        $user_id = $repo->find($id);

        $form = $this->createForm(Annonce2Type::class, $annonce);
                                                     
        $form->handleRequest($request);

        // dump($annonce); 

        if($form->isSubmitted() && $form->isValid()) {
            if (!$annonce->getId()) 
            {
                $annonce->setCreatedAt(new \DateTime());
                $annonce->setUser($user_id);
            }
           
            $manager->persist($annonce);
            $manager->flush();
            $this->addFlash('success', 'Votre annonce a bien été enregistrée !');
            return $this->redirectToRoute('blog_show', ['id' => $annonce->getId()]);

        }



        return $this->render('blog/depot_annonce.html.twig',[
            'formAnnonce' => $form->createView(),
            'editMode' => $annonce->getId()!== null,
            'userSS' => $user_id
        ]);
    }

     /**
     * @Route("/blog/{id}/delete", name="delete")
     */
    public function delete(Annonce $annonce)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($annonce);
        $em->flush();
        return $this->redirectToRoute('blog');
    }
    
    /**
     * @Route("/blog/{id}/show", name="blog_show")
     */
    public function show($id) 
    {
        $repo = $this->getDoctrine()->getRepository(Annonce::class);
        $annonce = $repo->find($id);
        $id_user = $repo->find($id)->getUser();

        $reponse = $this->getDoctrine()->getRepository(User::class);
        $user = $reponse->find($id_user);

        return $this->render('blog/show.html.twig',['annonce'=> $annonce,'user'=> $user]);
    }
    
    /**
     * @Route("/", name="blog")
     * @Route("", name="blog")
     */
    public function index(Request $request)
    {                
        $annonce = new Annonce;

        $form = $this->createForm(SelectionCategoryType::class, $annonce);
        $form->handleRequest($request);
        $categories = [ 'id' => null ];
        $repo = $this->getDoctrine()->getRepository(Annonce::class);  //permet d'aller chercher tous les annonces
        $annonces = $repo->findAll();  // la variable annonces est un array et on va le passer à twig

        if($form->isSubmitted() && $form->isValid())
        {
            $categories = $annonce->getCategory();
        }
 
        return $this->render('blog/index.html.twig', [
            'formCategory' => $form->createView(),
            'controller_name' => 'BlogController',
            'annonces' => $annonces,
            'categories' => $categories,
            'title' => "Bonjour et bienvenue sur notre site internet !"
        ]);
    }

    /**
     * @Route("/category", name="category")
     */
    public function category(Request $request)
    {                      
        $annonce = new Annonce;

        $form = $this->createForm(SelectionCategoryType::class, $annonce);
        $form->handleRequest($request);
        $categories = [ 'id' => null ];
        $repo = $this->getDoctrine()->getRepository(Annonce::class);  //permet d'aller chercher tous les annonces
        $annonces = $repo->findAll();  // la variable annonces est un array et on va le passer à twig

        if($form->isSubmitted() && $form->isValid())
        {
            $categories = $annonce->getCategory();
        }
 
        return $this->render('blog/category.html.twig', [
            'formCategory' => $form->createView(),
            'controller_name' => 'BlogController',
            'annonces' => $annonces,
            'categories' => $categories,
            'title' => "Bonjour et bienvenue sur notre site internet !"
        ]);
    }

    /**
     * @Route("/blog/compte", name="compte")
     */
    public function compte()
    {
        $identification = new User;

        $form = $this->createForm(IdentificationType::class, $identification);

        return $this->render('blog/compte.html.twig', [
            'formIdentification' => $form->createView() 
        ]);
    }

    /**
     * @Route("/blog/{id}/perso", name="annonce_personnel")
     */
    public function annoncePersonnel(User $user)
    {
        return $this->render('blog/annoncePersonnel.html.twig', [
            'user' => $user
        ]);
    }
}

templates/blog/annonce.html.twig
{% extends 'base.html.twig' %}

{% form_theme formAnnonce 'bootstrap_4_layout.html.twig' %}

{% block body %}

    <h1></h1>
    <h1 class="text-center mt-3">
        {% if editMode %}
            MODIFICATION DE L'ANNONCE
        {% else %}
             DEPOSER UNE ANNONCE
        {% endif %}
    </h1><hr>
    
    {{ form_start(formAnnonce) }}

        {{ form_row(formAnnonce.title, {'attr': {'placeholder': "titre de l'annonce"}} ) }}                       
        {# {{ form_row(formAnnonce.category) }}  #}
        {{ form_row(formAnnonce.Prix, {'attr': {'placeholder': "Prix de l'annonce"}} ) }}                              
        {{ form_row(formAnnonce.Image, {'attr': {'placeholder': "Image de l'annonce"}}) }}                                                                                           
        <button type="submit" class="btn btn-success">                  
            {% if editMode %}
                Enregistrer les modification
            {% else %}
                Ajouter l'annonce
            {% endif %}
        </button>                                                            
        
    {{ form_end(formAnnonce) }}

{% endblock %}

templates/blog/annoncePersonnel.html.twig
{% extends "base.html.twig" %}

{% block body %}

<h2 class="text-center my-5 col-md-3 mx-auto  p-2">Page personnelle</h2>
<hr>

    <div class="row d-flex justify-content-center m-5">

        <div class="col-md-4 rounded mx-auto" >
            {# <div class="rounded"> #}
                <div class="col-md-10 bg-dark rounded d-flex flex-column justify-content-center text-white text-center p-3">
                    <img class="mt-4 rounded" src="{{ asset('images/produits/' ~ user.image ) }}" alt="Card image cap"><hr>
                    <p id="divInfoPersoOff" class="p-2 rounded bg-secondary">{{ user.pseudo }}</p>
                    <p id="divInfoPersoOff" class="p-2 rounded bg-secondary"><i class="far fa-envelope mr-2"></i><a class="text-white" href="mailto:{{ user.email }}">{{ user.email|raw }}</a></p>
                    <p id="divInfoPersoOff" class="p-2 rounded bg-secondary"><i class="fas fa-phone-alt mr-2"></i>{{ user.telephone }}</p>
                    {% if app.user %}
                        <a id="divInfoPersoOn" class="p-2 rounded bg-primary text-white text-decoration-none" href="{{ path('modifierProfil', {'id': app.user.id}) }}">Mes Informations personnel</a>      
                    {% endif %}
                </div>
            {# </div> #}
        </div>

    </div>

    <div id="colorPerso" class="col-md-8 rounded border border-secondary mx-auto p-5 mb-5">
        <div class="col-md-12 d-flex justify-content-center mx-auto">

            <div id="colorPerso" class="row d-flex justify-content-center text-white">
                {% for annoncePersonnel in user.annonce %}
                    <div class="col-md-3 m-2 p-3 bg-secondary rounded border border-dark">
                        <img class="card-img-top" src="{{ asset('images/produits/' ~ annoncePersonnel.image ) }}" alt="Card image cap">
                            
                        <strong>{{ annoncePersonnel.title }}</strong>
                        <p>{{ annoncePersonnel.prix }} €</p>
                        <p class="text-right">Posté le {{ annoncePersonnel.CreatedAt|date('d/m/Y') }} à {{ annoncePersonnel.CreatedAt|date('H:i:s') }}</p>
                        
                        <div class="row d-flex-justify-content-end">
                            <div class="col-md-3"><a id="colorBtnInput " class="btn btn-success rounded text-white mb-2" href="{{ path('blog_show', {'id': annoncePersonnel.id} ) }}">Voir</a></div> 
                            <div class="col-md-3"></div>  {% if app.user.id == annoncePersonnel.user.id %}
                                <a id="colorBtnInput " class="btn rounded bg-white mr-2 ml-3 mb-2" href="{{ path('blog_show', {'id': annoncePersonnel.id} ) }}"><i style="color: rgb(160, 9, 127);" class="fas fa-pen"></i></a>
                            <div class="col-md-3"><a id="colorBtnInput " class="btn rounded bg-white mb-2" href="{{ path('blog_show', {'id': annoncePersonnel.id} ) }}"><i style="color: rgb(160, 9, 9);" class="far fa-trash-alt"></i></a></div> 
                            {% endif %}
                        </div> 
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    


{% endblock %}

templates/blog/category.html.twig
{% extends "base.html.twig" %}

{% block Categories %}

    <div class="col-md-4 rounded p-5 categories">                            
        {{form_start(formCategory)}}
            <div class="form-row">
                <div id="cadre-recherche" class="form-group col-md-11 rounded p-2 pl-5 pr-5 mx-auto m-0 text-white">
                    {{ form_row(formCategory.category) }}
                </div>
                <div class="mt-5 d-flex justify-content-center col-md-12">
                    <button type="submit" class="btn btn-success col-md-5 bouton-rechercher">Rechercher</button>
                </div>
            </div>
        {{form_end(formCategory)}}
    </div>

{% endblock %}
{% block body %}

    <section class="annonces row d-flex justify-content-center pt-5 pt-sm-0">
        <img class="col-12" src="images/naturewave.png" alt="PhotoPourRemplirLeVide">
        {% for annonce in annonces %}
            {% if annonce.category.id == categories.id %}

                <article class="col-md-3 border border-secondary rounded mr-5 mb-5 mt-5 text-center p-2 text-justify">
                    <img class="card-img-top" src="{{ asset('images/produits/' ~ annonce.image ) }}" alt="Card image cap">
                    {#<img src="{{ annonce.Image }}" alt="{{ annonce.title }}" class="col-md-12 rounded"><hr>#}
                    <h5>{{ annonce.title|slice(3, 25)|raw }}</h5>
                    <p> Prix : <span class="font-weight-bold" >{{ annonce.prix }}</span></p><hr>
                    <p> Catégorie : <span class="font-weight-bold" >{{ annonce.category.nom }}</span></p><hr>
                    <div class="metadata text-right m-3">Posté le {{annonce.createdAt | date('d/m/y') }} à {{annonce.createdAt | date('H:i') }}</div> 
                    <a href="{{ path('blog_show', {'id':annonce.id}) }}" class="btn btn-primary m-2">Voir l'annonce</a>
                </article>

            {% endif %}

        {% endfor %}
    </section>
    
{% endblock %}

templates/blog/compte.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <h1 class="display-4 my-4 mx-auto text-center">Inscription</h1>

    {{ form_start(formIdentification, { 'attr' : { 'class' : 'col-md-6 mx-auto mb-5' }}) }}

        {{ form_row(formIdentification.prenom) }}
        {{ form_row(formIdentification.nom) }}
        {{ form_row(formIdentification.civilite) }}
        {{ form_row(formIdentification.ville) }}
        {{ form_row(formIdentification.password) }}
        {{ form_row(formIdentification.confirm_password) }}
        {{ form_row(formIdentification.pseudo) }}
        {{ form_row(formIdentification.adresse) }}
        {{ form_row(formIdentification.birth) }}

    <form action="/action_page.php">
        <div class="form-group">
            <input class="form-controle mr-2" type="checkbox" id="cgv" name="cgv">
            <label for="vehicle1">J'accepte les Conditions Générales de Ventes</label><br>
        </div>
        
        <button class="btn btn-dark col-md-2" type="submit">S'incrire</button>
    </form>

    {{ form_end(formIdentification) }}
{% endblock %}

templates/blog/contact.html.twig
{% extends "base.html.twig" %}

{% block body %}
    
    {{ form_start(formContact, { 'attr' : { 'class' : 'my-4 col-md-4 mx-auto'}}) }}

        {{ form_row(formContact.firstname) }}
        {{ form_row(formContact.lastname) }}
        {{ form_row(formContact.phone) }}
        {{ form_row(formContact.email) }}
        {{ form_row(formContact.message) }}

        <button class="btn btn-dark col-md-2 my-4" type="submit">S'incrire</button>

    {{ form_end(formContact) }}

    

{% endblock %}

templates/blog/index.html.twig
{% extends "base.html.twig" %}

{% block Bienvenue %}

    <h1 id="titre-accueil" class='mx-auto text-white mb-5 text-center bienvenue ml-2 d-none d-sm-block'>{{ title }}</h1>
                        
{% endblock %}


{% block body %}
   
    <section class="annonces row d-flex justify-content-center mx-auto">
        {% for annonce in annonces %}

                <article class="col-md-3 border border-secondary rounded m-5 text-center bg-dark rounded m-3 p-2 text-white">
                    <img src="{{ annonce.Image }}" alt="{{ annonce.title }}" class="col-md-12 rounded"><hr>
                    <h2>{{ annonce.title|slice(3, 20)|raw  }}</h2>
                    <p> Prix : <span class="font-weight-bold" >{{ annonce.prix }}</span></p><hr>
                    <p> Catégory : <span class="font-weight-bold" >{{ annonce.category.nom }}</span></p><hr>
                    <div class="metadata">Posté le {{annonce.createdAt | date('d/m/y') }} à {{annonce.createdAt | date('H:i') }}</div> 
                    <a href="{{ path('blog_show', {'id':annonce.id}) }}" class="btn btn-primary m-3">Voir l'annonce</a>
                </article>

        {% endfor %}
    </section>

{% endblock %}

templates/blog/show.html.twig
{% extends "base.html.twig" %} 


{% block body %}
    


<div class="text-center">

    <div class=" d-flex justify-around m-3 p-2">
        <br>
        <br>

        <div class="col-md-7">
            <div  style=" box-shadow: 8px 8px 12px #aaa; padding: 2em 2em 0em 2em " class"" id="colorPerso" class=" pb-2 rounded border border-secondary">
                <article >

                    <img  style=" box-shadow: 8px 8px 12px rgb(36, 36, 36)" class="card-img-top   rounded" src="{{ asset('images/produits/' ~ annonce.image ) }}" alt="Card image cap">
                    {# <img src="{{ annonce.Image }}" alt="{{ annonce.title }}" class="col-md-12 rounded"> #}

                    <hr>
                    <h2>{{ annonce.title }}</h2>

                    <p>
                        Prix : {{ annonce.prix }}</p>
                    <hr>
                    <div class="metadata">Posté le {{annonce.createdAt | date('d/m/y') }} à {{annonce.createdAt | date('H:i') }} dans la categorie <strong>{{ annonce.category }}</strong>
                    </div>
                    <div class="row">
                        <div  class="col-md-3 text-center">
                            <a id="divInfoPersoOn" href="{{ path('blog') }}" class="btn btn-dark text-white rounded mb-2">Acceuil</a>
                        </div>
                    </div>
                </article>
            </div>
            {# ################################################################################################################################# #}
        </div>
        <div class="col-md-3">
            <div class="">

                    <div style=" box-shadow: 2px 2px 5px #aaa; padding: 2em 2em 0em 2em "  id="colorPerso" class="col-md-7 rounded ">

                        <div class="row d-flex justify-content-center ">
                            <h3>Contact</h3>
                            <p class="p-0 m-0"style="font-size:1.8 em;">Email: <strong>{{user.email|slice(3, 16)|raw }}</strong></p><hr>
                            <p style="font-size:1.8 em;">Tel: <strong>{{ user.telephone }}</strong></p><hr>
                            <p style="font-size:1.8 em;">Ville : <strong>{{user.ville}}</strong> </p><hr>
                            <p class="mr-3" style="font-size:1.8 em;">Adresse: <strong>{{user.adresse}}</strong></p><hr>
                            <a class="bg-dark p-2 m-2 rounded text-white" style="text-decoration: none;" href="{{ path('annonce_personnel', {'id':user.id}) }}">PAGE PERSONNEL</a><br>
                        
                        </div><hr>
                        

                    </div>
                </div>
            </div>
            <br>
           


        </div>

    </div>


    {% endblock %}